"""create user sessions

Revision ID: 0f11e35680eb
Revises: f7fa5f121d6e
Create Date: 2026-09-28 20:35:38.851576

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0f11e35680eb'
down_revision: Union[str, None] = 'f7fa5f121d6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_sessions',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False, comment='主键'),
    sa.Column('user_id', sa.Integer(), nullable=False, comment='用户ID'),
    sa.Column('token_hash', sa.String(length=64), nullable=False, comment='会话token哈希值'),
    sa.Column('create_time', sa.DateTime(), server_default=sa.text('(UTC_TIMESTAMP())'), nullable=False, comment='创建时间'),
    sa.Column('expire_time', sa.DateTime(), nullable=False, comment='过期时间'),
    sa.Column('revoke_time', sa.DateTime(), nullable=True, comment='撤销时间'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_user_sessions')),
    sa.UniqueConstraint('token_hash', name=op.f('uq_user_sessions_token_hash'))
    )
    op.create_index(op.f('ix_user_sessions_expire_time'), 'user_sessions', ['expire_time'], unique=False)
    op.create_index(op.f('ix_user_sessions_user_id'), 'user_sessions', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_sessions_user_id'), table_name='user_sessions')
    op.drop_index(op.f('ix_user_sessions_expire_time'), table_name='user_sessions')
    op.drop_table('user_sessions')
    # ### end Alembic commands ###
